name: CI/CD Pipeline

# Trigger the pipeline on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js (example for Node.js project)
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust version as needed
    
    - name: Install dependencies
      run: |
        npm install
    
    - name: Run tests
      run: |
        npx cypress run --spec "cypress/e2e/Web/Features/ChargePoint.feature,cypress/e2e/Web/Features/ChargePointAPI.feature"
    
    - name: Build project (optional)
      run: |
        npm run build
    
    - name: Deploy (optional)
      run: |
        # Deploy to your server or cloud platform here
        echo "Deploying project..."